% dot11_ltf_known_sequence.m
% This function returns the known LTF sequence in frequency domain.
%
% by Wuqiong Zhao <wqzhao@ucsd.edu>

function known_ltf_freq = dot11_ltf_known_sequence()
    num_total_subcarriers = 64;
    known_ltf_freq = zeros(num_total_subcarriers, 1);
    % Subcarrier indices from -26 to -1 and 1 to 26
    subcarrier_numbers = [-26:-1, 1:26];
    subcarrier_indices = dot11_ifft_index_map(subcarrier_numbers);
    ltf_values = [ ...
         ... % n from -26 to -1
         1,  1, -1, -1,  1,  1, -1,  1, ...
        -1,  1,  1,  1,  1,  1,  1, -1, ...
        -1,  1,  1, -1,  1, -1,  1,  1, ...
         1,  1, ...
         ... % n from +1 to +26
         1, -1, -1,  1,  1, -1,  1, -1, ...
         1, -1, -1, -1, -1, -1,  1,  1, ...
        -1, -1,  1, -1,  1, -1,  1,  1, ...
         1,  1 ...
    ]';
    known_ltf_freq(subcarrier_indices) = ltf_values;
end
